name: screenshot_desktop
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  objective_c: ^9.2.2
  hooks: ^0.20.5
  code_assets: ^0.19.10
  ffi: ^2.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  ffigen: ^20.1.1
  path: ^1.9.0
  logging: ^1.3.0
  native_toolchain_c: ^0.17.2
